# Generated by Django 3.2.9 on 2021-11-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_Profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='user', upload_to='avatar/')),
                ('cover', models.ImageField(default='covare', upload_to='cover/')),
                ('phone', models.IntegerField(default=0)),
                ('gander', models.CharField(choices=[('NO', 'Not Selected'), ('M', 'Male'), ('F', 'Female')], default=1, max_length=50)),
                ('country', models.CharField(blank=True, max_length=40)),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
                ('verification', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True)),
                ('earning', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('is_privet', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='profile_views', to='products.Ipaddrisse')),
            ],
        ),
    ]
