# Generated by Django 3.2.9 on 2021-11-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211115_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='covare.png', null=True, upload_to='cover/'),
        ),
    ]
