# Generated by Django 3.2.9 on 2021-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211115_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='cover.png', null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gander',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
