# Generated by Django 3.2.9 on 2021-11-10 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='CateImage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductImages')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ipaddrisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='StoreAvatar')),
                ('cover', models.ImageField(upload_to='StoreCover')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('follow', models.ManyToManyField(related_name='store_followers', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.storetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, to='products.Ipaddrisse')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0)),
                ('olde_price', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shiping_info', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_g', models.FloatField(blank=True, null=True, verbose_name='g ')),
                ('is_kg', models.FloatField(blank=True, null=True, verbose_name='Kg ')),
                ('shiping_type', models.CharField(choices=[('NO', 'Not Selected'), ('M', 'Free'), ('F', 'Buy')], default=1, max_length=30)),
                ('shiping_price', models.FloatField(blank=True, default=0, null=True)),
                ('cart', models.ManyToManyField(blank=True, related_name='add_to_cart', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categore')),
                ('color', models.ManyToManyField(related_name='product_color', to='products.Color')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.image')),
                ('like', models.ManyToManyField(blank=True, related_name='like_product', to=settings.AUTH_USER_MODEL)),
                ('save_product', models.ManyToManyField(related_name='save_product', to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(blank=True, related_name='product_size', to='products.Size')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='veiws', to='products.Ipaddrisse')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('not_confirm', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='customer_order', to='products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
