# Generated by Django 3.2.9 on 2021-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
