# Generated by Django 3.2.9 on 2021-11-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_store_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
