# Generated by Django 3.2.9 on 2021-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
